// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ExecuteRequest
 */
export type ExecuteRequest = {
    /**
     * Input
     */
    input: string;
    /**
     * Idempotency Key
     */
    idempotency_key: string;
};

/**
 * ExecutionPublic
 */
export type ExecutionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Id
     */
    workflow_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
    /**
     * Input
     */
    input: string;
    /**
     * Output
     */
    output: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string;
    /**
     * Status
     */
    status: 'pending' | 'running' | 'completed' | 'failed';
    /**
     * Prompt Tokens
     */
    prompt_tokens: number | null;
    /**
     * Completion Tokens
     */
    completion_tokens: number | null;
    /**
     * Total Tokens
     */
    total_tokens: number | null;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created By
     */
    created_by: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * GovernanceUpdate
 */
export type GovernanceUpdate = {
    /**
     * Daily Execution Limit
     */
    daily_execution_limit: number;
    /**
     * Max Concurrent Executions
     */
    max_concurrent_executions: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MemberPublic
 */
export type MemberPublic = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: 'owner' | 'admin' | 'member';
    /**
     * Created At
     */
    created_at: string;
};

/**
 * MemberWrite
 */
export type MemberWrite = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role?: 'admin' | 'member';
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Metrics
 */
export type Metrics = {
    /**
     * Workspaces
     */
    workspaces: number;
    /**
     * Workflows
     */
    workflows: number;
    /**
     * Executions
     */
    executions: number;
    /**
     * Successful Executions
     */
    successful_executions: number;
    /**
     * Failed Executions
     */
    failed_executions: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
    /**
     * Executions With Usage
     */
    executions_with_usage: number;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProviderPublic
 */
export type ProviderPublic = {
    /**
     * Id
     */
    id?: string;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Default Model
     */
    default_model: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowPublic
 */
export type WorkflowPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Provider
     */
    provider?: 'openai-compatible';
    /**
     * Model
     */
    model: string;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Output Tokens
     */
    max_output_tokens?: number;
    /**
     * Status
     */
    status?: 'active' | 'disabled';
    /**
     * Id
     */
    id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
    /**
     * Created By
     */
    created_by: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WorkflowWrite
 */
export type WorkflowWrite = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Provider
     */
    provider?: 'openai-compatible';
    /**
     * Model
     */
    model: string;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Max Output Tokens
     */
    max_output_tokens?: number;
    /**
     * Status
     */
    status?: 'active' | 'disabled';
};

/**
 * WorkspaceCreate
 */
export type WorkspaceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * WorkspacePublic
 */
export type WorkspacePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Daily Execution Limit
     */
    daily_execution_limit: number;
    /**
     * Max Concurrent Executions
     */
    max_concurrent_executions: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Role
     */
    role: 'owner' | 'admin' | 'member';
};

export type operationsListWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/workspaces';
};

export type operationsListWorkspacesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsListWorkspacesError = operationsListWorkspacesErrors[keyof operationsListWorkspacesErrors];

export type operationsListWorkspacesResponses = {
    /**
     * Response Operations-List Workspaces
     *
     * Successful Response
     */
    200: Array<WorkspacePublic>;
};

export type operationsListWorkspacesResponse = operationsListWorkspacesResponses[keyof operationsListWorkspacesResponses];

export type operationsCreateWorkspaceData = {
    body: WorkspaceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/workspaces';
};

export type operationsCreateWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsCreateWorkspaceError = operationsCreateWorkspaceErrors[keyof operationsCreateWorkspaceErrors];

export type operationsCreateWorkspaceResponses = {
    /**
     * Successful Response
     */
    201: WorkspacePublic;
};

export type operationsCreateWorkspaceResponse = operationsCreateWorkspaceResponses[keyof operationsCreateWorkspaceResponses];

export type operationsReadWorkspaceData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{workspace_id}';
};

export type operationsReadWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsReadWorkspaceError = operationsReadWorkspaceErrors[keyof operationsReadWorkspaceErrors];

export type operationsReadWorkspaceResponses = {
    /**
     * Successful Response
     */
    200: WorkspacePublic;
};

export type operationsReadWorkspaceResponse = operationsReadWorkspaceResponses[keyof operationsReadWorkspaceResponses];

export type operationsUpdateGovernanceData = {
    body: GovernanceUpdate;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{workspace_id}/governance';
};

export type operationsUpdateGovernanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsUpdateGovernanceError = operationsUpdateGovernanceErrors[keyof operationsUpdateGovernanceErrors];

export type operationsUpdateGovernanceResponses = {
    /**
     * Successful Response
     */
    200: WorkspacePublic;
};

export type operationsUpdateGovernanceResponse = operationsUpdateGovernanceResponses[keyof operationsUpdateGovernanceResponses];

export type operationsListMembersData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/workspaces/{workspace_id}/members';
};

export type operationsListMembersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsListMembersError = operationsListMembersErrors[keyof operationsListMembersErrors];

export type operationsListMembersResponses = {
    /**
     * Response Operations-List Members
     *
     * Successful Response
     */
    200: Array<MemberPublic>;
};

export type operationsListMembersResponse = operationsListMembersResponses[keyof operationsListMembersResponses];

export type operationsSetMemberData = {
    body: MemberWrite;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{workspace_id}/members';
};

export type operationsSetMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsSetMemberError = operationsSetMemberErrors[keyof operationsSetMemberErrors];

export type operationsSetMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberPublic;
};

export type operationsSetMemberResponse = operationsSetMemberResponses[keyof operationsSetMemberResponses];

export type operationsRemoveMemberData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{workspace_id}/members/{user_id}';
};

export type operationsRemoveMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsRemoveMemberError = operationsRemoveMemberErrors[keyof operationsRemoveMemberErrors];

export type operationsRemoveMemberResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type operationsRemoveMemberResponse = operationsRemoveMemberResponses[keyof operationsRemoveMemberResponses];

export type operationsListWorkflowsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/workspaces/{workspace_id}/workflows';
};

export type operationsListWorkflowsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsListWorkflowsError = operationsListWorkflowsErrors[keyof operationsListWorkflowsErrors];

export type operationsListWorkflowsResponses = {
    /**
     * Response Operations-List Workflows
     *
     * Successful Response
     */
    200: Array<WorkflowPublic>;
};

export type operationsListWorkflowsResponse = operationsListWorkflowsResponses[keyof operationsListWorkflowsResponses];

export type operationsCreateWorkflowData = {
    body: WorkflowWrite;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{workspace_id}/workflows';
};

export type operationsCreateWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsCreateWorkflowError = operationsCreateWorkflowErrors[keyof operationsCreateWorkflowErrors];

export type operationsCreateWorkflowResponses = {
    /**
     * Successful Response
     */
    201: WorkflowPublic;
};

export type operationsCreateWorkflowResponse = operationsCreateWorkflowResponses[keyof operationsCreateWorkflowResponses];

export type operationsReadWorkflowData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type operationsReadWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsReadWorkflowError = operationsReadWorkflowErrors[keyof operationsReadWorkflowErrors];

export type operationsReadWorkflowResponses = {
    /**
     * Successful Response
     */
    200: WorkflowPublic;
};

export type operationsReadWorkflowResponse = operationsReadWorkflowResponses[keyof operationsReadWorkflowResponses];

export type operationsUpdateWorkflowData = {
    body: WorkflowWrite;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}';
};

export type operationsUpdateWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsUpdateWorkflowError = operationsUpdateWorkflowErrors[keyof operationsUpdateWorkflowErrors];

export type operationsUpdateWorkflowResponses = {
    /**
     * Successful Response
     */
    200: WorkflowPublic;
};

export type operationsUpdateWorkflowResponse = operationsUpdateWorkflowResponses[keyof operationsUpdateWorkflowResponses];

export type operationsExecuteWorkflowData = {
    body: ExecuteRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_id}/execute';
};

export type operationsExecuteWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsExecuteWorkflowError = operationsExecuteWorkflowErrors[keyof operationsExecuteWorkflowErrors];

export type operationsExecuteWorkflowResponses = {
    /**
     * Successful Response
     */
    200: ExecutionPublic;
};

export type operationsExecuteWorkflowResponse = operationsExecuteWorkflowResponses[keyof operationsExecuteWorkflowResponses];

export type operationsListExecutionsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/workspaces/{workspace_id}/executions';
};

export type operationsListExecutionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsListExecutionsError = operationsListExecutionsErrors[keyof operationsListExecutionsErrors];

export type operationsListExecutionsResponses = {
    /**
     * Response Operations-List Executions
     *
     * Successful Response
     */
    200: Array<ExecutionPublic>;
};

export type operationsListExecutionsResponse = operationsListExecutionsResponses[keyof operationsListExecutionsResponses];

export type operationsReadExecutionData = {
    body?: never;
    path: {
        /**
         * Execution Id
         */
        execution_id: string;
    };
    query?: never;
    url: '/api/v1/executions/{execution_id}';
};

export type operationsReadExecutionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsReadExecutionError = operationsReadExecutionErrors[keyof operationsReadExecutionErrors];

export type operationsReadExecutionResponses = {
    /**
     * Successful Response
     */
    200: ExecutionPublic;
};

export type operationsReadExecutionResponse = operationsReadExecutionResponses[keyof operationsReadExecutionResponses];

export type operationsMetricsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Workspace Id
         */
        workspace_id?: string | null;
    };
    url: '/api/v1/operations/metrics';
};

export type operationsMetricsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type operationsMetricsError = operationsMetricsErrors[keyof operationsMetricsErrors];

export type operationsMetricsResponses = {
    /**
     * Successful Response
     */
    200: Metrics;
};

export type operationsMetricsResponse = operationsMetricsResponses[keyof operationsMetricsResponses];

export type operationsProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/operations/providers';
};

export type operationsProvidersResponses = {
    /**
     * Response Operations-Providers
     *
     * Successful Response
     */
    200: Array<ProviderPublic>;
};

export type operationsProvidersResponse = operationsProvidersResponses[keyof operationsProvidersResponses];

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
