"""Add workspace isolation, workflows, and execution usage metadata.

Revision ID: a4f120260905
Revises: fe56fa70289e
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

revision = "a4f120260905"
down_revision = "fe56fa70289e"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('daily_execution_limit', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_executions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('daily_execution_limit BETWEEN 1 AND 10000', name='workspace_daily_execution_limit_check'),
    sa.CheckConstraint('max_concurrent_executions BETWEEN 1 AND 20', name='workspace_max_concurrent_executions_check'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)
    op.create_table('workspacemember',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='workspacemember_role_check'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('aiworkflow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='aiworkflow_status_check'),
    sa.CheckConstraint('max_output_tokens BETWEEN 1 AND 8192', name='aiworkflow_max_output_tokens_check'),
    sa.CheckConstraint('temperature BETWEEN 0 AND 2', name='aiworkflow_temperature_check'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'workspace_id')
    )
    op.create_index(op.f('ix_aiworkflow_workspace_id'), 'aiworkflow', ['workspace_id'], unique=False)
    op.create_table('aiexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='aiexecution_status_check'),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0 AND total_tokens >= 0', name='aiexecution_check'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id', 'workspace_id'], ['aiworkflow.id', 'aiworkflow.workspace_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'created_by', 'idempotency_key')
    )
    op.create_index(op.f('ix_aiexecution_created_at'), 'aiexecution', ['created_at'], unique=False)
    op.create_index(op.f('ix_aiexecution_workflow_id'), 'aiexecution', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_aiexecution_workspace_id'), 'aiexecution', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("aiexecution")
    op.drop_table("aiworkflow")
    op.drop_table("workspacemember")
    op.drop_table("workspace")
